{
 "title": "New dashboard",
 "time": { "from": "2025-07-27T06:40:27.612Z", "to": "2025-07-27T10:12:28.311Z" },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average (1/5/15)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Memory (bytes/MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/etc/hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}